import browserify from "browserify";
import FS from "fs";
import Logger from "@thaerious/logger";
const logger = Logger.getLogger();

function renderJS(sourcePath, nidgetDependencies, outputPath){
    logger.channel("very-verbose").log(`  \\_ ${sourcePath}`);

    return new Promise((resolve, reject) => {
        const b = browserify({ debug: true });   
        b.add(sourcePath);

        for (let record of nidgetDependencies) {
            
            if (record.script){
                logger.channel("very-verbose").log(`    \\_ ${record.script}`);
                b.add(record.script);
            } else {
                logger.channel("very-verbose").log(`    \\_ X ${record.name}`);
            }
        }

        b.transform("babelify");
        const rs = b.bundle();
        
        const stream = FS.createWriteStream(outputPath);
        stream.write("// generated by EJSRender on " + new Date().toLocaleString() + "\n");  

        rs.on('error', err => {     
            if (stream?.emit) stream.emit('end');    
            stream?.close();
            reject(err);
        });
        
        rs.pipe(stream);
        
        // wait for the write-stream to finish writing
        stream.on('finish', ()=>{
            stream.close();
            resolve();
        });     
    });
}

export default renderJS;
